[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "platform"
version = "0.1.0"
description = "graph visualizer platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["api"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["core*"]

[tool.pytest.ini_options]
pythonpath = ["..", "."]
